/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransaksiRouteImport } from './routes/_authenticated/transaksi'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedPengaturanIndexRouteImport } from './routes/_authenticated/pengaturan.index'
import { Route as AuthenticatedPengaturanPicRouteImport } from './routes/_authenticated/pengaturan.pic'
import { Route as AuthenticatedPengaturanKategoriRouteImport } from './routes/_authenticated/pengaturan.kategori'
import { Route as AuthenticatedPengaturanDataRouteImport } from './routes/_authenticated/pengaturan.data'
import { Route as AuthenticatedPengaturanAplikasiRouteImport } from './routes/_authenticated/pengaturan.aplikasi'
import { Route as AuthenticatedPengaturanAboutRouteImport } from './routes/_authenticated/pengaturan.about'
import { Route as AuthenticatedPengaturanBudgetIndexRouteImport } from './routes/_authenticated/pengaturan.budget.index'
import { Route as AuthenticatedPengaturanBudgetIdRouteImport } from './routes/_authenticated/pengaturan.budget.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransaksiRoute = AuthenticatedTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanIndexRoute =
  AuthenticatedPengaturanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanPicRoute =
  AuthenticatedPengaturanPicRouteImport.update({
    id: '/pic',
    path: '/pic',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanKategoriRoute =
  AuthenticatedPengaturanKategoriRouteImport.update({
    id: '/kategori',
    path: '/kategori',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanDataRoute =
  AuthenticatedPengaturanDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanAplikasiRoute =
  AuthenticatedPengaturanAplikasiRouteImport.update({
    id: '/aplikasi',
    path: '/aplikasi',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanAboutRoute =
  AuthenticatedPengaturanAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanBudgetIndexRoute =
  AuthenticatedPengaturanBudgetIndexRouteImport.update({
    id: '/budget/',
    path: '/budget/',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)
const AuthenticatedPengaturanBudgetIdRoute =
  AuthenticatedPengaturanBudgetIdRouteImport.update({
    id: '/budget/$id',
    path: '/budget/$id',
    getParentRoute: () => AuthenticatedPengaturanRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRouteWithChildren
  '/transaksi': typeof AuthenticatedTransaksiRoute
  '/pengaturan/about': typeof AuthenticatedPengaturanAboutRoute
  '/pengaturan/aplikasi': typeof AuthenticatedPengaturanAplikasiRoute
  '/pengaturan/data': typeof AuthenticatedPengaturanDataRoute
  '/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/pengaturan/pic': typeof AuthenticatedPengaturanPicRoute
  '/pengaturan/': typeof AuthenticatedPengaturanIndexRoute
  '/pengaturan/budget/$id': typeof AuthenticatedPengaturanBudgetIdRoute
  '/pengaturan/budget/': typeof AuthenticatedPengaturanBudgetIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/transaksi': typeof AuthenticatedTransaksiRoute
  '/': typeof AuthenticatedIndexRoute
  '/pengaturan/about': typeof AuthenticatedPengaturanAboutRoute
  '/pengaturan/aplikasi': typeof AuthenticatedPengaturanAplikasiRoute
  '/pengaturan/data': typeof AuthenticatedPengaturanDataRoute
  '/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/pengaturan/pic': typeof AuthenticatedPengaturanPicRoute
  '/pengaturan': typeof AuthenticatedPengaturanIndexRoute
  '/pengaturan/budget/$id': typeof AuthenticatedPengaturanBudgetIdRoute
  '/pengaturan/budget': typeof AuthenticatedPengaturanBudgetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRouteWithChildren
  '/_authenticated/transaksi': typeof AuthenticatedTransaksiRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pengaturan/about': typeof AuthenticatedPengaturanAboutRoute
  '/_authenticated/pengaturan/aplikasi': typeof AuthenticatedPengaturanAplikasiRoute
  '/_authenticated/pengaturan/data': typeof AuthenticatedPengaturanDataRoute
  '/_authenticated/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/_authenticated/pengaturan/pic': typeof AuthenticatedPengaturanPicRoute
  '/_authenticated/pengaturan/': typeof AuthenticatedPengaturanIndexRoute
  '/_authenticated/pengaturan/budget/$id': typeof AuthenticatedPengaturanBudgetIdRoute
  '/_authenticated/pengaturan/budget/': typeof AuthenticatedPengaturanBudgetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/laporan'
    | '/pengaturan'
    | '/transaksi'
    | '/pengaturan/about'
    | '/pengaturan/aplikasi'
    | '/pengaturan/data'
    | '/pengaturan/kategori'
    | '/pengaturan/pic'
    | '/pengaturan/'
    | '/pengaturan/budget/$id'
    | '/pengaturan/budget/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/laporan'
    | '/transaksi'
    | '/'
    | '/pengaturan/about'
    | '/pengaturan/aplikasi'
    | '/pengaturan/data'
    | '/pengaturan/kategori'
    | '/pengaturan/pic'
    | '/pengaturan'
    | '/pengaturan/budget/$id'
    | '/pengaturan/budget'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/laporan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/transaksi'
    | '/_authenticated/'
    | '/_authenticated/pengaturan/about'
    | '/_authenticated/pengaturan/aplikasi'
    | '/_authenticated/pengaturan/data'
    | '/_authenticated/pengaturan/kategori'
    | '/_authenticated/pengaturan/pic'
    | '/_authenticated/pengaturan/'
    | '/_authenticated/pengaturan/budget/$id'
    | '/_authenticated/pengaturan/budget/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaksi': {
      id: '/_authenticated/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof AuthenticatedTransaksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan/': {
      id: '/_authenticated/pengaturan/'
      path: '/'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof AuthenticatedPengaturanIndexRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/pic': {
      id: '/_authenticated/pengaturan/pic'
      path: '/pic'
      fullPath: '/pengaturan/pic'
      preLoaderRoute: typeof AuthenticatedPengaturanPicRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/kategori': {
      id: '/_authenticated/pengaturan/kategori'
      path: '/kategori'
      fullPath: '/pengaturan/kategori'
      preLoaderRoute: typeof AuthenticatedPengaturanKategoriRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/data': {
      id: '/_authenticated/pengaturan/data'
      path: '/data'
      fullPath: '/pengaturan/data'
      preLoaderRoute: typeof AuthenticatedPengaturanDataRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/aplikasi': {
      id: '/_authenticated/pengaturan/aplikasi'
      path: '/aplikasi'
      fullPath: '/pengaturan/aplikasi'
      preLoaderRoute: typeof AuthenticatedPengaturanAplikasiRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/about': {
      id: '/_authenticated/pengaturan/about'
      path: '/about'
      fullPath: '/pengaturan/about'
      preLoaderRoute: typeof AuthenticatedPengaturanAboutRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/budget/': {
      id: '/_authenticated/pengaturan/budget/'
      path: '/budget'
      fullPath: '/pengaturan/budget/'
      preLoaderRoute: typeof AuthenticatedPengaturanBudgetIndexRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
    '/_authenticated/pengaturan/budget/$id': {
      id: '/_authenticated/pengaturan/budget/$id'
      path: '/budget/$id'
      fullPath: '/pengaturan/budget/$id'
      preLoaderRoute: typeof AuthenticatedPengaturanBudgetIdRouteImport
      parentRoute: typeof AuthenticatedPengaturanRoute
    }
  }
}

interface AuthenticatedPengaturanRouteChildren {
  AuthenticatedPengaturanAboutRoute: typeof AuthenticatedPengaturanAboutRoute
  AuthenticatedPengaturanAplikasiRoute: typeof AuthenticatedPengaturanAplikasiRoute
  AuthenticatedPengaturanDataRoute: typeof AuthenticatedPengaturanDataRoute
  AuthenticatedPengaturanKategoriRoute: typeof AuthenticatedPengaturanKategoriRoute
  AuthenticatedPengaturanPicRoute: typeof AuthenticatedPengaturanPicRoute
  AuthenticatedPengaturanIndexRoute: typeof AuthenticatedPengaturanIndexRoute
  AuthenticatedPengaturanBudgetIdRoute: typeof AuthenticatedPengaturanBudgetIdRoute
  AuthenticatedPengaturanBudgetIndexRoute: typeof AuthenticatedPengaturanBudgetIndexRoute
}

const AuthenticatedPengaturanRouteChildren: AuthenticatedPengaturanRouteChildren =
  {
    AuthenticatedPengaturanAboutRoute: AuthenticatedPengaturanAboutRoute,
    AuthenticatedPengaturanAplikasiRoute: AuthenticatedPengaturanAplikasiRoute,
    AuthenticatedPengaturanDataRoute: AuthenticatedPengaturanDataRoute,
    AuthenticatedPengaturanKategoriRoute: AuthenticatedPengaturanKategoriRoute,
    AuthenticatedPengaturanPicRoute: AuthenticatedPengaturanPicRoute,
    AuthenticatedPengaturanIndexRoute: AuthenticatedPengaturanIndexRoute,
    AuthenticatedPengaturanBudgetIdRoute: AuthenticatedPengaturanBudgetIdRoute,
    AuthenticatedPengaturanBudgetIndexRoute:
      AuthenticatedPengaturanBudgetIndexRoute,
  }

const AuthenticatedPengaturanRouteWithChildren =
  AuthenticatedPengaturanRoute._addFileChildren(
    AuthenticatedPengaturanRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRouteWithChildren
  AuthenticatedTransaksiRoute: typeof AuthenticatedTransaksiRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRouteWithChildren,
  AuthenticatedTransaksiRoute: AuthenticatedTransaksiRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
